image: debian:bullseye

before_script:
  - apt-get update && apt-get -qy install fdroidserver wget --no-install-recommends
  - echo $fdroid_keystore_base64 | base64 -d >keystore.bks
  - chmod 600 fdroid/config.yml keystore.bks
  - mkdir -p fdroid/repo

stages:
  - build
  - deploy

build_repo:
  stage: build
  script:
  - (cd fdroid/repo && while read -r line || [ -n "$line" ]; do rm -f $line; done < ../../cleanup.txt)
  - ./download.py
  - cd fdroid
  - >-
    echo "keypass: $fdroid_keypass">>config.yml
  - >-
    echo "keystorepass: $fdroid_keystorepass">>config.yml
  - yamllint metadata/
  - fdroid lint
  - fdroid update
  - rm -rf archive
  - mkdir /fdroid && fdroid deploy
  - rm -rf /fdroid/archive
  - cd .. && mkdir public && mv -v /fdroid public
  - echo "Repo size:" && du -h -d 3 public
  - ls -al public/fdroid/repo/
  - CHECK=$(du -sb public | cut -f1) && if [ ${CHECK} -gt 1000000000 ]; then echo "Repo too large" && false; fi
  artifacts:
    when: always
    paths:
      - public

pages:
  stage: deploy
  script: echo "publish to Gitlab pages"
  artifacts:
    paths:
    - public
    expire_in: 4 weeks
  only:
  - master
  - schedules
  cache:
    paths:
    - fdroid
