image: openjdk:latest

before_script:
  - apt-get update && apt-get -y install fdroidserver
  - chmod 600 config.py

pages:
  stage: deploy
  script:
  - fdroid lint
  - fdroid update --create-key --create-metadata
  - mkdir /fdroid && fdroid server update
  - cp -R /fdroid public
  artifacts:
    paths:
    - public
  only:
  - master
